name: Deploy to Kubernetes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: irlansuzano/guia-infnet

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false # Não executa pnpm install automaticamente aqui

      - name: Install dependencies
        # Usar --frozen-lockfile é a prática recomendada para CI
        # Certifique-se que seu pnpm-lock.yaml está atualizado e commitado
        run: pnpm install --frozen-lockfile

      - name: Setup Next.js cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          # Chave de cache ajustada para depender apenas do lockfile
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Build application
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: irlansuzano
          password: ${{ secrets.ENV_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Kubernetes
        if: false
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            guia-deployment.yaml
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          namespace: default
